### PR TITLE
electron: fix relaunches on linux

### PR DESCRIPTION
**Pull request by matildepark**
Set up a VMWare install of Ubuntu, added a catch for AppImages. When I build on Linux, go to the unpacked folder and then run ./scene, the relaunch behaviour now works. Dev environment does not, because it is not an AppImage.

For some reason, the AppImage itself does not work on my Ubuntu 20.05 (shared library isn't found)? I am assuming it is some transient issue in the VMWare environment, or just using an older version of Ubuntu, but need confirmation. 

I also need to test this real quick on Mac to see if the relaunch still works with the additional options here.

### CODE REVIEW

**Comment by matildepark** [comment]
Mac works. Weirdly the previous `process.send()` error also gone. Probably unrelated ...

**Review by ixv — COMMENTED** [review]
Can confirm it works on arch. Would be nice to make sure it works on ubuntu, since I've seen some ubuntu users complain about this.

**Comment by matildepark** [comment]
I am not sure what else I’m supposed to do there. I have reasonable confidence it does based on what’s in front of me. I guess I could open the prebuild from ci?

**Comment by matildepark** [comment]
@ixv Confirmed working on Ubuntu 22.04 LTS — ran into https://github.com/AppImage/AppImageKit/issues/1092 because of virtualisation on arm64.

**Review by ixv — APPROVED** [review]

**Pull request merged**
