### PR TITLE
Drag fixes

### PR DESCRIPTION
**Pull request by yungcalibri**
Fixes janky vertical dragging.

Sets minimum dimensions for the Scene window at 1024x768, and for individual apps at 800x600.

Expands the area windows can be dragged through, such that the smallest sized windows can be hidden but not completely lost. 

Also memoized sorting and prepping notifications, and prettier in a few spots. 

don't make fun of me for this screencap 

- memoize notification ordering
- prettier
- improve draggable area
- expand draggable area
- add minwidth and minheight for windows
- fix janky vertical dragging
- set window minimum height

### CODE REVIEW

**Comment by tacryt-socryp** [comment]
Looks fantastic! Great job

**Comment by ixv** [comment]
The minimum size thing is a bit wonky with a window manager. In dwm it just stays the same size while other windows overflow it.

**Comment by ixv** [comment]
Would probably be fine if we just reduced the minimum size. 1024x768 is a bit big for a minimum, its like half my screen.

**Comment by yungcalibri** [comment]
Ok @ixv I took it out for you just because I like anything tiled

**Comment by ixv** [comment]
perfect, thanks

**Review by ixv — APPROVED** [review]

**Pull request merged**
