### PR TITLE
Launchpad: distinguish suspended tiles

### LINKED ISSUE #33: launchpad: display suspended states for apps

### PR DESCRIPTION
**Pull request by matildepark**
Fixes #33

### CODE REVIEW

**Comment by matildepark** [comment]
@ixv was mentioning "why not just filter out suspended tiles?" I wanna make this a fair replacement for Grid; #39 and surfacing Grid settings (#42 underlying issue) would do this without needing people to use Grid to remove suspended apps.

**Review by ixv — COMMENTED** [review]
Sounds good, we should still manually filter out old groups though. Its good to have parity with web grid even if its kind of wack.

**Comment by matildepark** [comment]
I mean, old Groups still functions. Why hide it from the user? New users won't get Groups 1 on boot, but pre-existing users could still feasibly use it.

**Comment by matildepark** [comment]
Are we good to just merge this @ixv? Maybe deploy a new version tn?

**Review by ixv — APPROVED** [review]

**Pull request merged**
