### PR TITLE
various: rewrite notifications

### PR DESCRIPTION
**Pull request by matildepark**
- Hark API changed, but old endpoint worked for *some* notifications. We just migrate to the new API now, porting in Tlon's new APIs.
- New notifications are strongly grouped and don't always perfectly correlate their origin to a URL — sometimes they need a `/` leading, sometimes not, based on DMs vs. Groups for example, and then of course non-globbed apps don't have a leading `/apps` at all. We do our best to derive the notification source and inject it into the open window, if we have one, or we spawn right to it.
- We change all logic for focusing windows to filter by the window's originating desk, not the full charge, so we can rewrite charge hrefs when spawning windows.
- You can't dismiss notifications, just mark them as seen. So we do so when opening the menu, a la macOS.

Probably needs cursory testing. I tried a few scenarios to shake it out, but there's probably others. The style is also a bit different — can I make the others resemble this?

Screenshot 2023-02-10 at 12 28 42 PM

### CODE REVIEW

**Comment by matildepark** [comment]
One more thing to note is that "new channel" notifications from Groups launch to a blank page because Groups itself crashes when hitting that view directly.

**Comment by matildepark** [comment]
- Notifications should fade out
- Scrollbar should be invisible
- Add "latestYarn" var and a clear button and if latest yarn is there, we slice up to that point

**Review by ixv — APPROVED** [review]

**Comment by matildepark** [comment]
Notifications have a little half opacity box so not sure if we really need a fade out. All menus match this. All prompts + windows get color from the background. I added a latest yarn catch so that you can hide all previous notifications. Hid scrollbar.

Screenshot 2023-02-14 at 1 23 23 PM

**Comment by matildepark** [comment]
@ixv: This should be good now. Basically our colour swatches were too precise when dealing with limited colors in an image (decimal values, not integers), and when we were deriving white or black text from the color we expected integers. 

This is reassuring, because I added catches for `null` values everywhere and was confused when another one arrived ... it was just in the theme derivation logic (yet again).

Oddly, it finds a red in the noise when scaling the image up. At least it's contrast:

Screenshot 2023-02-15 at 9 26 17 AM

**Pull request merged**
